version: '2.2'

services:
  web:
    build:
      context: .
      dockerfile: ./.config/dev/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./:/home/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir : /home/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Asia/Seoul
      - POSTGRES_USER=dkinno
      - POSTGRES_PASSWORD=east0518
      - POSTGRES_DB=lunch

volumes:
  postgres_data: